image:
  repository: penguinade/igx-dns-sync
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2023.02.01.02"

imagePullSecrets: []

serviceAccount:
  name: "dns-sync-account"

providers:
  cloudFlare:
    apiToken:

controller:
  nodeSelector:
    kubernetes.io/os: linux
