apiVersion: v1
kind: Service
metadata:
  name: dns-sync
spec:
  selector:
    app: dns-sync
  ports:
    - name: https
      port: 443
      targetPort: 443

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: dns-sync-webhook
webhooks:
- name: "dns-sync.ingress.kubernetes.io"
  rules:
  - apiGroups:   ["extensions", "networking.k8s.io"]
    apiVersions: ["v1", "v1beta1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["ingresses"]
    scope:       "*"
  clientConfig:
    service:
      name: "dns-sync"
      namespace: "ingress-nginx"
      path: "/validating-webhook"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5

---

# Reference: ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-sync-account

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-sync
spec:
  selector:
    matchLabels:
      app: dns-sync
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-sync
    spec:
      containers:
        - name: app
          image: 192.168.80.4:32000/dns-sync:b00008
          env:
            - name: CA_CERT
              value: /certs/cert
            - name: CA_KEY
              value: /certs/key
          volumeMounts:
            - name: webhook-cert
              mountPath: /certs/
              readOnly: true
      volumes:
        - name: webhook-cert
          secret:
            secretName: dns-sync
      serviceAccount: dns-sync-account

---

# Reference: ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-sync-crole
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---

# Reference: ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-sync-crole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-sync-crole
subjects:
  - kind: ServiceAccount
    name: dns-sync-account
    namespace: ingress-nginx

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-sync-role
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dns-sync-role
subjects:
  - kind: ServiceAccount
    name: dns-sync-account

---

# Reference: ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: dns-sync-create
  labels:
    app: dns-sync
spec:
  template:
    metadata:
      name: dns-sync
      labels:
        app: dns-sync
    spec:
      containers:
        - name: create
          image: docker.io/jettech/kube-webhook-certgen:v1.5.1
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=dns-sync,dns-sync.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name=dns-sync
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccount: dns-sync-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000

---

# Reference: ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: dns-sync-patch
  labels:
    app: dns-sync
spec:
  template:
    metadata:
      name: dns-sync-patch
      labels:
        app: dns-sync
    spec:
      containers:
        - name: patch
          image: docker.io/jettech/kube-webhook-certgen:v1.5.1
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --webhook-name=dns-sync-webhook
            - --namespace=$(POD_NAMESPACE)
            - --patch-mutating=false
            - --secret-name=dns-sync
            - --patch-failure-policy=Fail
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: dns-sync-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
