apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-sync-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:     ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dns-sync-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
